### ISSUE TITLE
Drupal multisite tutorial

### ISSUE THREAD

**Issue by pirog** [lando/docs#110]

**Comment by nalipaz** [comment]
I guess I will drudge this issue back up since my repo does seem to be the most referenced and forked as an example of how to do this. I refactored my entire repo to better simplify how things work in a multisite setup on acquia. Here is a list of some notable changes:

1. Moved any scripts needed under `.lando/` directory and rewrote a bit of the lando `acquia-pull.sh` script to support multisites, not sure if this should really be pulled into the core recipe but I think it an improvement. The only issue is I have yet to test it under a solo site.
2. The multisite namespaces must match the database names. This could be modified to no longer be a requirement but I didn't have the time or willingness to deal with it.
3. No default site. To simplify the scripting I just did away with the default site in the install I was working with and all sites are in their own named databases.
4. Databases are now created all under one host, rather than firing up a bunch of database hosts!
5. Drush Alias file example is provided for ease of running drush commands
6. You must make the modifications and changes under the outlined sites directory and any files noted in the README.md.
7. I have moved the old version of the repo to a branch called `legacy-master`.

I hope others get use out of this. This is a very clean and minimal version that took some experimenting to create. It does however fix up being able to use `lando pull` among other things. I also have tooling in my own project that works off all of this to do things like `yarn tasks` for any themes and things like that.
