### ISSUE TITLE
404 error when opening full documentation from the proxy 101 page

### ISSUE THREAD

**Issue by SimJoSt** [lando/docs#209]
Hey, I noticed, that on https://docs.lando.dev/lando-101/lando-proxy.html the link at the end to the full documentation leads to a 404 error. The URL is perfectly correct, and reloading immediately shows the page and content without any errors.

It seems that there is some inconsistency in the Vue SPA magic. I don't know enough about it, to supply a PR with a fix.  
My only guess is something I noticed in the code. In some situations, `.md` is used as a file extension, in others it's `.html`. It doesn't seem consistent and after rendering, everything ends with `.html`. Also, some paths are absolute, while others are relative.
+ Relative path & `.md` file extension: https://github.com/lando/docs/blob/main/getting-started/installation.md?plain=1#L58
+ Absolute path & `.html` file extension: https://github.com/lando/docs/blob/main/lando-101/lando-proxy.md?plain=1#L56

**Comment by alisonjo315** [comment]
I was about to open a new issue, but I think it might be similar enough to this one to go in a comment here...? -- but happy to create a new issue if other disagree!

The links to "CLI" documentation on the Help > Logs page are broken / throw 404 errors:
https://docs.lando.dev/help/logs.html
* Just one example (there are several): The link to lando logs (under [Container Logs](https://docs.lando.dev/help/logs.html#container-logs)) ends up here:
`https://docs.lando.dev/cli%2Flogs.html`
* The link URL looks right, buuut obviously it gets coded wrong.  (Correct URL: https://docs.lando.dev/cli/logs.html)

I'm not sure the right way to code this kind of link in a vuepress universe (or any Vue universe!), all I can think of is that it's because the destination page [is in a different repo](https://github.com/lando/cli/tree/main/docs) -- but I still don't know how to fix it, unless the fix is to use an absolute link!

https://github.com/lando/docs/blob/a290f80241631616d167728feb3a02d5c96c7155/help/logs.md

**Comment by alisonjo315** [comment]
Discussed on lando community Slack, and I think all of these links need to be changed to absolute, because they're going to different docs repos.

* Original issue: The "full proxy documentation" URL when it finally resolves is: https://docs.lando.dev/core/v3/proxy.html
  * Meaning, it's part of Core repo: https://github.com/lando/core/tree/main/docs
* My comment about lando logs: The documentation pages linked to from the lando logs page have URLs like this: https://docs.lando.dev/cli/logs.html
  * Meaning, they're are all housed in the CLI repo: https://github.com/lando/cli/tree/main/docs

-------
To fix, the broken URLs we're finding in this repo should be replaced with absolute URLs.

❓ Question: Are they supposed to be links to ".md" URLs or ".html" URLs...?  My gut feeling is they should be the html URLs, but I really don't know how vuepress works!

**Comment by alisonjo315** [comment]
_(I guess it's obviously, but I'm saying it in a comment anyway! -- )_

I created a PR to replace the relative links with absolute links, on the two pages we've been talking about: #225

**Comment by SimJoSt** [comment]
As I don't know enough about the infrastructure and Vue SPAs or VuePress, I'll close the issue regarding the url I mentioned. It now works on the first try. If there are any additional adjustments to be made to fix more bugs or streamline the docs, feel free to open it again.
