### ISSUE TITLE
Add instructions for developing offline with Linux

### ISSUE THREAD

**Issue by gitressa** [lando/docs#39]
**Link to the page that needs to be updated or changed.**
There is a page about how to work off-line:
https://docs.lando.dev/guides/offline-dev.html

... with instructions specifically for Mac:
https://docs.lando.dev/guides/offline-dev.html#mac-specific-instructions

**Describe the change you'd like**
It would be nice with a list of the minimal steps required for developing offline with Linux (Ubuntu) as well.

**Comment by gitressa** [comment]
This would still be great, has anyone managed to do this? If you share it, I will gladly add it to the documentation.

**Comment by stingray21** [comment]
I was working on this over the past week, and found a "working" solution for myself. But I haven't tested it extensively nor am I an expert on the topic. I am happy to write it down to for the docs, but I am hesitant since I do not know whether it is really the correct way to do it, and I haven't gotten any feedback yet (in the lando slack or stackoverflow).

## Issues I encountered 
- NetworkManager was overwriting `/etc/resolv.conf`, so whatever changes I made, where reverted by running `sudo systemctl restart NetworkManager` [Arch Wiki:NetworkManager](https://wiki.archlinux.org/title/NetworkManager#Unmanaged_/etc/resolv.conf)
- Missing certs in firefox [Lando Docs](https://docs.lando.dev/config/security.html#arch)

## Working version
 1. add this line to`/etc/dnsmasq.conf` :
    ```
    address=/local.host/127.0.0.1
    ```
 2. leave `/etc/hosts` as is
 3. create file `/etc/NetworkManager/conf.d/dns.conf` with content:
    ```
    [main]
    dns=none
    ```
 4. change content of `/etc/resolv.conf` to (important:`nameserver 127.0.0.1` is before `nameserver 192.168.2.1`)
    ```
    search speedport.ip
    nameserver 127.0.0.1
    nameserver 192.168.2.1
    nameserver fe80::1%enp0s20u2u4
    ```
 5. run 
    ```shell
    sudo systemctl restart NetworkManager
    sudo systemctl restart dnsmasq
    ```
 6. add this line to `~/.lando/config.yml`
    ```
    domain: local.host
    ```
 7. run 
    ```shell 
    lando poweroff
    lando rebuild -y
    ```
 8. run 
    ```shell
    sudo trust anchor ~/.lando/certs/local.host.pem
    sudo trust anchor ~/.lando/certs/local.host.crt
    ```

https://superuser.com/questions/1718192/how-to-set-up-dnsmasq-under-linux-to-use-a-wildcard-domain-for-local-web-develop

**Comment by stingray21** [comment]
I don't not know whether the first and fourth lines are needed, they were already in the file. I don't know that much about this topic, therefore my approach was to change as little as possible. I only added the second line (`nameserver 127.0.0.1`) and left the rest untouched, 
`speedport.ip` is for the configuration of speedport routers (instead of http://192.168.2.1). But I didn't actively added it, not sure how got added.
